# Generated by Django 3.2.3 on 2021-05-17 16:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('film', '0002_auto_20210516_2222'),
    ]

    operations = [
        migrations.CreateModel(
            name='likeUnlikefilm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trueOrNot', models.IntegerField()),
                ('Film', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='namefile', to='film.film')),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='makelike', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
