# Generated by Django 3.2.3 on 2021-05-17 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interact', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='likeunlikefilm',
            old_name='trueOrNot',
            new_name='true_or_not',
        ),
    ]
