# Generated by Django 2.2.5 on 2021-06-15 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interact', '0002_rename_trueornot_likeunlikefilm_true_or_not'),
    ]

    operations = [
        migrations.DeleteModel(
            name='likeUnlikefilm',
        ),
    ]
