# Generated by Django 3.2.3 on 2021-05-17 17:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('film', '0002_auto_20210516_2222'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='reviewOfFilm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minutesOfwitch', models.IntegerField(null=True)),
                ('precent', models.IntegerField()),
                ('Film', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='namefileUser', to='film.film')),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nameUser', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
