# Generated by Django 2.2.5 on 2021-06-15 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('film', '0004_auto_20210615_2153'),
        ('categories', '0002_alter_categories_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='categories',
        ),
    ]
