# Generated by Django 2.2.5 on 2021-06-15 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='searchhistory',
        ),
    ]
