# Generated by Django 3.2.3 on 2021-05-16 21:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('film', '0002_auto_20210516_2222'),
    ]

    operations = [
        migrations.CreateModel(
            name='actors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('film', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actorfilm', to='film.film')),
            ],
        ),
    ]
