# Generated by Django 3.2.3 on 2021-05-16 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('film', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='film',
            old_name='linkOfFilm',
            new_name='link_of_film',
        ),
        migrations.RenameField(
            model_name='film',
            old_name='productionCompany',
            new_name='production_company',
        ),
        migrations.RenameField(
            model_name='film',
            old_name='releaseDate',
            new_name='release_date',
        ),
        migrations.RenameField(
            model_name='film',
            old_name='runTime',
            new_name='run_time',
        ),
        migrations.RenameField(
            model_name='film',
            old_name='spokenLanguage',
            new_name='spoken_language',
        ),
    ]
