# Generated by Django 3.2.3 on 2021-05-17 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('film', '0002_auto_20210516_2222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='link_of_film',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
