# Generated by Django 2.2.5 on 2021-07-02 23:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('film', '0004_auto_20210615_2153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acotors_film',
            name='actors',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actor', to='film.actors'),
        ),
        migrations.AlterField(
            model_name='acotors_film',
            name='films',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='films', to='film.film'),
        ),
    ]
