# Generated by Django 3.2 on 2021-07-05 10:13

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('film', '0006_auto_20210705_1309'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='search_history',
            new_name='search_histor',
        ),
    ]
