# Generated by Django 3.2 on 2021-07-05 10:17

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('film', '0007_rename_search_history_search_histor'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='search_histor',
            new_name='search_history',
        ),
    ]
