# Generated by Django 3.2 on 2021-07-05 10:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('film', '0008_rename_search_histor_search_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='actor',
            field=models.ManyToManyField(through='film.acotors_film', to='film.actors'),
        ),
        migrations.AlterField(
            model_name='search_history',
            name='films',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='searchuser', to='film.film'),
        ),
    ]
