# Generated by Django 3.2 on 2021-07-05 10:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('film', '0009_auto_20210705_1332'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='review',
            field=models.ManyToManyField(related_name='review_of_film', through='film.review_of_film', to=settings.AUTH_USER_MODEL),
        ),
    ]
