# Generated by Django 3.2 on 2021-07-05 10:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('film', '0010_film_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='search',
            field=models.ManyToManyField(related_name='search_history', through='film.search_history', to=settings.AUTH_USER_MODEL),
        ),
    ]
