# Generated by Django 3.2 on 2021-07-12 17:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('film', '0015_film_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='interact',
            field=models.ManyToManyField(related_name='like_un_like_film', through='film.like_un_like_film', to=settings.AUTH_USER_MODEL),
        ),
    ]
