# Generated by Django 3.2 on 2021-07-12 17:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('film', '0017_film_search'),
    ]

    operations = [
        migrations.CreateModel(
            name='origin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.RemoveField(
            model_name='film',
            name='categorie',
        ),
        migrations.AddField(
            model_name='film',
            name='origins',
            field=models.ForeignKey(default=20, on_delete=django.db.models.deletion.CASCADE, related_name='origin', to='film.origin'),
            preserve_default=False,
        ),
    ]
