# Generated by Django 3.2 on 2021-07-12 18:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('film', '0019_auto_20210712_2043'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='actor',
            field=models.ManyToManyField(through='film.acotors_film', to='film.actors'),
        ),
        migrations.AddField(
            model_name='film',
            name='interact',
            field=models.ManyToManyField(related_name='like_un_like_film', through='film.like_un_like_film', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='film',
            name='review',
            field=models.ManyToManyField(related_name='review_of_film', through='film.review_of_film', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='film',
            name='search',
            field=models.ManyToManyField(related_name='search_history', through='film.search_history', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='categories_film',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categori', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categori', to='film.categories')),
                ('films', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='filmsCategories', to='film.film')),
            ],
        ),
        migrations.AddField(
            model_name='film',
            name='categorie',
            field=models.ManyToManyField(related_name='categories_film', through='film.categories_film', to='film.categories'),
        ),
    ]
