# Generated by Django 3.2 on 2021-07-12 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('film', '0020_auto_20210712_2106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='production_company',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='film',
            name='spoken_language',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
