# Generated by Django 3.2.5 on 2021-08-29 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('film', '0022_auto_20210812_2043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='film',
            name='production_company',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='film',
            name='rate',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='film',
            name='run_time',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='film',
            name='title',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='review_of_film',
            name='precent_rate',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='search_history',
            name='Text',
            field=models.TextField(),
        ),
    ]
