# Generated by Django 3.2.5 on 2021-08-30 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('film', '0023_auto_20210829_1738'),
    ]

    operations = [
        migrations.AlterField(
            model_name='director',
            name='name',
            field=models.CharField(max_length=20),
        ),
    ]
